
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstoneproj5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstoneproj5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: capstoneproj5
    spec:
      containers:
      - name: capstone
        image: satz0205/capstoneproj5:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: capstoneproj5-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: capstoneproj5
  ports:
    - protocol: TCP
      port: 80