version: 2.1

orbs:
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.3
  aws-cli: circleci/aws-cli@2.0.3

jobs:
  build-lint:
    docker:
# Use the same Docker base as the project
      - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - checkout
        # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv proj5
            . proj5/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ./proj5
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      # run lint!
      - run:
          name: run lint
          command: |
            . proj5/bin/activate
              make lint 
  
  build-image:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build-image
          command: |
            docker build -t capstoneproj5 .  
            docker image ls
      - run:
          name: upload-image
          command: |
            dockerpath=satz0205/capstoneproj5
            docker login -u="satz0205" -p="Eduku@0205"
            docker image tag capstoneproj5 $dockerpath
            docker push $dockerpath

  cluster-creation:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - run:
          name: install_awscli
          command: |
            apk add --update tar gzip nodejs npm curl
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            ./aws/install 
      - run:
          name: eks_install
          command: |
            apk add --update tar gzip nodejs npm curl
            curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
            mv /tmp/eksctl /usr/local/bin
            eksctl version     
      - run:
          name: kubetctl_install
          command: |
            curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.24.11/2023-03-17/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
            kubectl version --client
      - run:
          name: AWS EKS cluster creation
          community.aws.eks_cluster:
            name: proj5-cluster
            region: us-east-1
          nodeGroups:
            name: nodegroup1
            instanceType: t3.micro
            desiredCapacity: 2

workflows:
  default:
    jobs:
    #  - build-lint
    #  - build-image:
    #      requires[build-lint]
      - cluster-creation
  
          