version: 2.1

orbs:
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.3

executors:
  docker-publisher:
    environment:
      DOCKER_IMAGE: satz0205/capstoneproj5:latest
    docker:
      - image: docker:stable

jobs:
  buildlint:
    docker:
# Use the same Docker base as the project
      - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - checkout
        # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv proj5
            . proj5/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ./proj5
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      # run lint!
      - run:
          name: run lint
          command: |
            . proj5/bin/activate
              make lint 

  imagepush:
    executors: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: docker image
          command: docker build --tag ${DOCKER_IMAGE} .
      - run:
          name: List docker images
          command: docker image ls
     - run:
          name: Publish Docker image
          command: |
            docker login -u="sat0205" -p="Eduku@0205"
            docker push ${DOCKER_IMAGE}

workflows:
  default:
    jobs:
      - buildlint
      - imagepush
          